CREATE TABLE IF NOT EXISTS game (
id UUID NOT NULL PRIMARY KEY,
nbOfRound SMALLINT NOT NULL,
mapWidth SMALLINT NOT NULL,
mapHeight SMALLINT NOT NULL,
nbOfWizard SMALLINT NOT NULL,
nbObstacle SMALLINT NOT NULL,
winner VARCHAR (255) NOT NULL,
posting_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);