version: '3.6'
networks:
  internal-net:
   name: harrypottergame_subnet
services:
  backend:
    image: openjdk:11.0.1
    container_name: harrypottergame-api-container
    ports:
      - "8080:8080"
    networks:
      - internal-net
    volumes:
      - ./HarryPotterGameApi/build/libs:/opt/assets/
    command: java -jar /opt/assets/harrypotterapi-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
  proxy:
    image: nginx:latest
    container_name: harrypottergame-front-container
    ports:
      - "7501:80"
    volumes:
      - ./HarryPotterGameJs/dist/HarryPotterGameJS:/usr/share/nginx/html
      - ./HarryPotterGameJs/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=jjserver.ovh
      - NGINX_PORT=80
    networks:
      - internal-net
  db:
    image: postgres:12
    container_name: postgres-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: harrypottergame
      PGDATA: /var/lib/postgresql/data/pgdata